<template>
  <apply-form-item data="批复文件">
    <div>
      <p style="margin-top:0pt; margin-bottom:0pt; line-height:30pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-bottom:0pt; line-height:30pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:38pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:15pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:38pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:15pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:30pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:15pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-bottom:0pt; text-align:right; line-height:28pt; widows:0; orphans:0"><a name="文号2"><span style="font-family:仿宋_GB2312; font-size:16pt">文物保</span><span style="font-family:仿宋_GB2312; font-size:16pt">函</span><span style="font-family:仿宋_GB2312; font-size:16pt">〔</span></a><a name="文号3"><span style="-aw-bookmark-end:文号2"></span><span style="font-family:'Times New Roman'; font-size:16pt">2020</span><span style="font-family:仿宋_GB2312; font-size:16pt">〕</span></a><span style="font-family:'Times New Roman'; font-size:16pt">85</span><span style="font-family:仿宋_GB2312; font-size:16pt">号</span></p>
      <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:28pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:28pt; widows:0; orphans:0"><span style="font-family:方正小标宋简体; font-size:22pt; letter-spacing:-0.3pt">国家文物局关于番国故城保护范围内环境整治和服务设施建设项目意见的函</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">河南省文物局：</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">你局《关于报批固始县番国故城遗址公园（一期）建设工程设计方案的请示》（豫文物〔</span><span style="font-family:'Times New Roman'; font-size:16pt">2019</span><span style="font-family:仿宋_GB2312; font-size:16pt">〕</span><span style="font-family:'Times New Roman'; font-size:16pt">226</span><span style="font-family:仿宋_GB2312; font-size:16pt">号）收悉。经研究，我局原则同意在番国故城保护范围内实施环境整治和服务设施建设</span><span style="font-family:仿宋_GB2312; font-size:16pt">项目</span><span style="font-family:仿宋_GB2312; font-size:16pt">。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">一、所报方案尚需做以下必要的修改和完善：</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（一）加强考古资料梳理和研究，开展必要的考古工作，明确该区域城门、道路、护城河等重要遗迹位置，统筹考虑公园建设与番国故城整体保护展示工作的衔接，为科学确定番国故城展示体系和遗址公园建设内容、空间布局、景观设计等提供依据。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（二）应优化工程方案设计，坚持最小干预原则，合理确定环境整治区域和服务设施建设数量、选址、规模等：</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt">1.</span><span style="font-family:'Times New Roman'; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">不同意设置</span><span style="font-family:仿宋_GB2312; font-size:16pt">“</span><span style="font-family:仿宋_GB2312; font-size:16pt">凌空步道</span><span style="font-family:仿宋_GB2312; font-size:16pt">”</span><span style="font-family:仿宋_GB2312; font-size:16pt">。公园内部导览系统应增加遗址历史元素，展示和阐释遗址文化内涵。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt">2.</span><span style="font-family:'Times New Roman'; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">城墙南侧鱼塘回填应客观评估墙体土壤含水率变化及其影响，避免造成墙体结构稳定性问题，并制定必要的加固措施和预案；城墙北侧应预留安全距离，避免景观水系长期冲刷、掏蚀城墙本体。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt">3.</span><span style="font-family:'Times New Roman'; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">大规模移除城墙上现状乔木应慎重，城墙两侧景观设计不宜种植深根系植物，建议尽量选用本地植物品种，并保持历史氛围。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt">4.</span><span style="font-family:'Times New Roman'; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">明确游客服务中心、停车场、活动广场、草阶广场、文化剧院、儿童广场等新建设施高度、建设面积、外观样式、地面铺装形式，说明具体设计内容和经济技术指标，严格控制设施数量和规模，确保与遗址景观风貌相协调。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（三）不同意城墙缺损部分复原、整体封护等文物本体工程措施，涉及文物本体保护项目应按程序另行报批。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（四）严格工程范围和施工强度，做好施工中的文物保护工作，确保文物安全。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">二、请你局组织专业考古研究单位，在项目拟建区域进一步开展全面的考古调查和发掘工作，考古发掘项目需另行填报考古发掘申请书。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">三、请你局指导相关单位根据以上意见对所报项目进行修改、完善，并按照《中华人民共和国文物保护法》的有关规定，履行相应审批手续后实施。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">四、请你局会同相关部门加强对项目实施过程的全程监管，组织专业机构参与指导，确保文物安全。项目实施过程中如有文物遗存等重要发现，应立即停止施工并组织研究，提出调整方案。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">五、请你局督促地方人民政府统筹考虑番国故城保护利用工作，科学论证建设考古遗址公园的必要性和可行性，明确思路和措施，促进文物保护利用与城市建设发展相协调。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:32pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">专此函复。</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:30pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:15pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:30pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="width:39pt; text-indent:0pt; display:inline-block; -aw-tabstop-align:left; -aw-tabstop-pos:69pt">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:1.8pt; margin-bottom:0pt; text-indent:30pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="width:39pt; text-indent:0pt; display:inline-block; -aw-tabstop-align:left; -aw-tabstop-pos:69pt">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:86.55pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:仿宋_GB2312; font-size:16pt">国家文物局</span></p>
      <p style="margin-top:0pt; margin-right:60pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt">2020</span><span style="font-family:仿宋_GB2312; font-size:16pt">年</span><span style="font-family:'Times New Roman'; font-size:16pt">1</span><span style="font-family:仿宋_GB2312; font-size:16pt">月</span><span style="font-family:'Times New Roman'; font-size:16pt">20</span><span style="font-family:仿宋_GB2312; font-size:16pt">日</span></p>
      <p style="margin-top:0pt; margin-right:67.95pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:67.95pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:67.95pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:67.95pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:67.95pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:67.95pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:67.95pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:67.95pt; margin-bottom:0pt; text-align:right; line-height:27pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:72pt; margin-bottom:0pt; text-align:justify; line-height:5pt; widows:0; orphans:0"><span style="font-family:'Times New Roman'; font-size:16pt; -aw-import:ignore">&nbsp;</span></p>
      <p style="margin-top:0pt; margin-right:58.5pt; margin-bottom:0pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="font-family:黑体; font-size:14pt; -aw-import:spaces">&nbsp; </span><span style="font-family:黑体; font-size:14pt">公开形式：</span><span style="font-family:黑体; font-size:14pt">依申请</span><span style="font-family:黑体; font-size:14pt">公开</span></p>
      <p style="margin-top:0pt; margin-right:4.05pt; margin-bottom:0pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><a name="印发日期"><span style="height:0pt; text-align:left; display:block; position:absolute; z-index:1"></span><span style="font-family:仿宋_GB2312; font-size:14pt"> </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp;</span><span style="font-family:仿宋_GB2312; font-size:14pt">国家文物局办公室秘书处</span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp;&nbsp; </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp;</span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp; </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp;</span><span style="font-family:仿宋_GB2312; font-size:14pt"> </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp; </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp;&nbsp; </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp;</span><span style="font-family:仿宋_GB2312; font-size:14pt"> </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp;</span><span style="font-family:仿宋_GB2312; font-size:14pt"> </span></a><span style="font-family:'Times New Roman'; font-size:14pt">2020</span><span style="font-family:仿宋_GB2312; font-size:14pt">年</span><span style="font-family:'Times New Roman'; font-size:14pt">1</span><span style="font-family:仿宋_GB2312; font-size:14pt">月</span><span style="font-family:'Times New Roman'; font-size:14pt">20</span><span style="font-family:仿宋_GB2312; font-size:14pt">日印</span><span style="font-family:仿宋_GB2312; font-size:14pt">发</span></p>
      <p style="margin:0pt 15pt; text-align:justify; line-height:28pt; widows:0; orphans:0"><span style="height:0pt; text-align:left; display:block; position:absolute; z-index:0"></span><span style="font-family:仿宋_GB2312; font-size:14pt">初校：</span><span style="font-family:仿宋_GB2312; font-size:14pt">刘清</span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp; </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp;</span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp;&nbsp; </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp; </span><span style="font-family:仿宋_GB2312; font-size:14pt; -aw-import:spaces">&nbsp; </span><span style="font-family:仿宋_GB2312; font-size:14pt">终校</span><span style="font-family:仿宋_GB2312; font-size:14pt">：</span><span style="font-family:仿宋_GB2312; font-size:14pt">陈起</span></p>
      <div style="-aw-headerfooter-type:footer-primary">
        <div style="float:right">
          <p style="margin-top:0pt; margin-bottom:0pt; widows:0; orphans:0; font-size:14pt"><span style="-aw-field-start:true"></span><span style="-aw-field-code:'PAGE  '"></span><span style="-aw-field-separator:true"></span><span style="font-family:宋体">1</span><span style="-aw-field-end:true"></span><span style="font-family:宋体; -aw-import:spaces">&nbsp; </span></p>
        </div>
        <p style="margin-top:0pt; margin-right:18pt; margin-bottom:0pt; text-indent:18pt; widows:0; orphans:0; font-size:14pt"><span style="font-family:'Times New Roman'; -aw-import:ignore">&nbsp;</span></p>
      </div>
    </div>
  </apply-form-item>
</template>

<script>
  import ApplyFormItem from '@/components/commons/ApplyForm/ApplyFormItem'

  export default {
    components: {
      ApplyFormItem
    },
    data() {
      return {
        type: 'card' // list
      }
    },
    mounted() {

    },
    methods: {}
  }
</script>

<style lang="scss" scoped>

</style>
